version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: news-ai-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  news-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-ai
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/newsai
    volumes:
      - ./src/data/articles:/app/src/data/articles:ro
      - ./prisma:/app/prisma:ro
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: news-ai-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - news-ai
    restart: unless-stopped
    networks:
      - default

volumes:
  postgres_data:
    name: news-ai-postgres-data
